// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-X89w34CRpXhsYj-yg11GP6xAZqtEWM',
    appId: '1:755324536390:web:5c0990ad75b624269aec47',
    messagingSenderId: '755324536390',
    projectId: 'portfolio-300c3',
    authDomain: 'portfolio-300c3.firebaseapp.com',
    storageBucket: 'portfolio-300c3.appspot.com',
    measurementId: 'G-XCRCBL3FRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHHYfnrhzawOnMubdlzyKIV-OnpFeJksY',
    appId: '1:755324536390:android:5eae78da0261c3809aec47',
    messagingSenderId: '755324536390',
    projectId: 'portfolio-300c3',
    storageBucket: 'portfolio-300c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtHfF3jJ2isRhoc702rehlFFwSUyQ8c-Q',
    appId: '1:755324536390:ios:1682adbd2a990b279aec47',
    messagingSenderId: '755324536390',
    projectId: 'portfolio-300c3',
    storageBucket: 'portfolio-300c3.appspot.com',
    iosClientId: '755324536390-ovi75d7m4c1slmbm38rqsja23u82603o.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtHfF3jJ2isRhoc702rehlFFwSUyQ8c-Q',
    appId: '1:755324536390:ios:1682adbd2a990b279aec47',
    messagingSenderId: '755324536390',
    projectId: 'portfolio-300c3',
    storageBucket: 'portfolio-300c3.appspot.com',
    iosClientId: '755324536390-ovi75d7m4c1slmbm38rqsja23u82603o.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
